# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: fullstack-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: ./server          # ← путь к папке server
      dockerfile: Dockerfile
    container_name: fullstack-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/myapp?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
    expose:
      - "5000"

  nginx:
    build:
      context: .                 # ← контекст всего проекта
      dockerfile: Dockerfile.nginx
    container_name: fullstack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
